// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YellowCarrot.Data;

#nullable disable

namespace YellowCarrot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221215193327_Initail")]
    partial class Initail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeTags", b =>
                {
                    b.Property<int>("RecipesRecipeId")
                        .HasColumnType("int");

                    b.Property<string>("TagsName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecipesRecipeId", "TagsName");

                    b.HasIndex("TagsName");

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("YellowCarrot.Models.Ingredient", b =>
                {
                    b.Property<int>("IngridientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngridientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("IngridientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngridientId = 1,
                            Name = "Lasagna noodles",
                            Quantity = "9",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 2,
                            Name = "Italian sausage",
                            Quantity = "450 g",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 3,
                            Name = "Groud beef",
                            Quantity = "340 g",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 4,
                            Name = "Onion",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 5,
                            Name = "Garlic",
                            Quantity = "3 cloves",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 6,
                            Name = "Crushed tomatoes",
                            Quantity = "2 can",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 7,
                            Name = "Tomatoe paste",
                            Quantity = "2 cans",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 8,
                            Name = "Parsley",
                            Quantity = "300 g",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 9,
                            Name = "Basil",
                            Quantity = "2 teaspoons",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 10,
                            Name = "Salt",
                            Quantity = "300 g",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 11,
                            Name = "Egg",
                            Quantity = "1 lasge",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 12,
                            Name = "Ricotta cheese",
                            Quantity = "1 carton",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 13,
                            Name = "Mozzarella cheese",
                            Quantity = "4 cups",
                            RecipeId = 1
                        },
                        new
                        {
                            IngridientId = 14,
                            Name = "Parmesan cheese",
                            Quantity = "300 g",
                            RecipeId = 1
                        });
                });

            modelBuilder.Entity("YellowCarrot.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Name = "Lasagna"
                        });
                });

            modelBuilder.Entity("YellowCarrot.Models.Tags", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Name");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Name = "Italian"
                        });
                });

            modelBuilder.Entity("RecipeTags", b =>
                {
                    b.HasOne("YellowCarrot.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YellowCarrot.Models.Tags", null)
                        .WithMany()
                        .HasForeignKey("TagsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YellowCarrot.Models.Ingredient", b =>
                {
                    b.HasOne("YellowCarrot.Models.Recipe", "Recipe")
                        .WithMany("Ingridients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("YellowCarrot.Models.Recipe", b =>
                {
                    b.Navigation("Ingridients");
                });
#pragma warning restore 612, 618
        }
    }
}
